In [1]:
import numpy as np   # Import NumPy for numerical operations

# ---------------------------
# 1. Creating Simple NumPy Arrays
# ---------------------------

# Array of Virat Kohli's runs in 4 matches
virat_runs = np.array([72, 45, 88, 101])
print(virat_runs)

# 2D array representing team runs:
# Each row = player, each column = match
team_runs = np.array([
    [72, 45, 88],     # Virat
    [55, 60, 47],     # Rohit
    [30, 75, 50]      # Rahul
])
print(team_runs)

# Array of player ages
player_ages = np.array((35, 37, 31))
print(player_ages)


[ 72  45  88 101]
[[72 45 88]
 [55 60 47]
 [30 75 50]]
[35 37 31]


In [2]:
# ---------------------------
# 2. Special Arrays
# ---------------------------

# Array filled with zeros (2 rows, 3 columns)
zeros = np.zeros((2, 3))
print(zeros)

# Array filled with ones (3 rows, 2 columns)
ones = np.ones((3, 2))
print(ones)

# Identity matrix (3x3) — diagonal = 1, others = 0
identify = np.eye(3)
print(identify)

# Empty array — values are not initialized (random memory values)
empty = np.empty((2, 4))
print(empty)

# Array filled with a specific value (7)
full = np.full((2, 2), 7)
print(full)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[7 7]
 [7 7]]


In [3]:
# ---------------------------
# 3. Creating Arrays Using arange()
# ---------------------------

# Values from 55 to 64
arr1 = np.arange(55, 65)
print(arr1)

[55 56 57 58 59 60 61 62 63 64]


In [4]:
# ---------------------------
# 4. Random Number Generation
# ---------------------------

# Strike rates: 10 random float values between 100 and 200
strike_rates = np.random.uniform(100, 200, 10)
print(strike_rates)

# Random runs between 1 and 150 in a 2x3 matrix
runs = np.random.randint(1, 151, (2, 3))
print(runs)

# Batting averages (normally distributed around mean=35, sd=7)
batting_avg = np.random.normal(35, 7, (3, 4))
print(batting_avg)

[124.42297154 134.68275751 115.42956081 160.09517075 151.38771552
 155.32632008 176.0595204  191.15265923 118.01067495 135.2453071 ]
[[ 42  96 100]
 [ 36  13 122]]
[[43.88449475 24.93923452 26.73951698 49.64387523]
 [35.37947016 30.87793126 40.97884746 36.86348263]
 [44.552003   43.50700246 43.91520416 36.77849236]]


In [5]:
# ---------------------------
# 5. Appending to Arrays
# ---------------------------

arr = np.arange(0, 10)
new_arr_single = np.append(arr, 10)            # Append one value
new_arr_multiple = np.append(arr, [10, 11, 12]) # Append multiple values

print(arr)
print(new_arr_single)
print(new_arr_multiple)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
# ---------------------------
# 6. Reshaping Arrays
# ---------------------------

# Marks from 50 to 61
marks = np.arange(50, 62)
print(marks)

# Reshaping into 3 rows and 4 columns
reshaped = marks.reshape(3, 4)
print(reshaped)

[50 51 52 53 54 55 56 57 58 59 60 61]
[[50 51 52 53]
 [54 55 56 57]
 [58 59 60 61]]
