In [10]:
import pandas as pd
from scipy import stats

In [11]:
df = pd.read_csv('titanic.csv')

df.head()

survived  pclass  gender   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [12]:
print(df.survived.value_counts())
print(df.pclass.value_counts())

survived
0    549
1    342
Name: count, dtype: int64
pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [13]:
contingency_table = pd.crosstab(df['survived'], df['pclass'])

chi2_stat, p_value, degree_of_freedom, expected = stats.chi2_contingency(contingency_table)

print(chi2_stat)
print(degree_of_freedom)
print(p_value)
print(contingency_table)
print(expected)

102.88898875696056
2
4.549251711298793e-23
pclass      1   2    3
survived              
0          80  97  372
1         136  87  119
[[133.09090909 113.37373737 302.53535354]
 [ 82.90909091  70.62626263 188.46464646]]


In [14]:
# Find if gender and smoking are related in the trips dataset

df1 = pd.read_csv('tips.csv')

df1.head()

total_bill   tip  gender smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  
0  Christy Cunningham  3.560330e+15    Sun2959  
1      Douglas Tucker  4.478070e+15    Sun4608  
2      Travis Walters  6.011810e+15    Sun4458  
3    Nathaniel Harris  4.676140e+15    Sun5260  
4        Tonya Carter  4.832730e+15    Sun2251

In [15]:
print(df1.gender.value_counts())
print(df1.smoker.value_counts())

gender
Male      157
Female     87
Name: count, dtype: int64
smoker
No     151
Yes     93
Name: count, dtype: int64


In [16]:
contingency_table = pd.crosstab(df1['gender'], df1['smoker'])

chi2_stat, p_value, dof, expected = stats.chi2_contingency(contingency_table)

In [17]:
print(chi2_stat)
print(dof)
print(p_value)
print(contingency_table)
print(expected)

0.0
1
1.0
smoker  No  Yes
gender         
Female  54   33
Male    97   60
[[53.84016393 33.15983607]
 [97.15983607 59.84016393]]


In [18]:
import numpy as np

df2 = pd.read_csv('diabetes.csv')
conditions = [(df2['Age'] <= 30), ((df2['Age'] > 30) & (df2['Age'] <= 50)), (df2['Age'] > 50)]
group = ['Young', 'Middle', 'Old']
df2['Age_group'] = np.select(conditions, group, default='Unknown')

df2.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome Age_group  
0                     0.627   50        1    Middle  
1                     0.351   31        0    Middle  
2                     0.672   32        1    Middle  
3                     0.167   21        0     Young  
4                     2.288   33        1    Middle

In [19]:
df2['Age_group'].value_counts()
df2['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [20]:
contingency_table = pd.crosstab(df2['Age_group'], df2['Outcome'])

chi2_stat, p_value, dof, expected = stats.chi2_contingency(contingency_table)

print(chi2_stat)
print(dof)
print(p_value)
print(contingency_table)
print(expected)

71.85015965734874
2
2.499977318493404e-16
Outcome      0    1
Age_group          
Middle     130  140
Old         43   38
Young      327   90
[[175.78125   94.21875 ]
 [ 52.734375  28.265625]
 [271.484375 145.515625]]
